---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image is published to ghcr.io/pboling/galtzo-os
name: galtzo-os
# description will be included in the image's metadata
description: Aurora DX (beta) with NordVPN, 1Password, asus-linux, and other tweaks

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: beta # latest is also supported if you want new, but stable, updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - 1password.repo
      - asus-linux.repo
      - ghostty.repo
      - nordvpn.repo
    optfix:
      - 1Password
    install:
      - micro
      # NOTE: starship should be installed via brew install starship,
      #       since the rpm-ostree module is not maintained
      # - starship
      # Necessary to install Ruby
      # See: https://github.com/rbenv/ruby-build/wiki#fedora
      - autoconf
      - gcc
      - gcc-c++
      - rust
      - patch
      - make
      - bzip2
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - readline-devel
      - gdbm-devel
      - ncurses-devel
      - perl-FindBin # Because of OpenSSL!
      # Necessary for JRuby & dynamodb-local
      - java-25-openjdk-devel
      # Necessary for Quality of Life
      - nordvpn
      - 1password
      # CLI to manage filesystem snapshots, primarily for Btrfs and LVM with ext4
      - snapper
      # For ASUS laptops, to manage fan profiles and other hardware features
      - asusctl
      - asusctl-rog-gui
      # Terminal
      - ghostty

  - type: script
    scripts:
      - fix-zlib-symlink.sh

  - type: systemd
    system:
      enabled:
        - nordvpnd

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
